import { BPReading } from '../types';

export const INITIAL_SAMPLE_READINGS: BPReading[] = [
  {
    id: 'rd-01',
    timestamp: new Date(Date.now() - 28 * 86400000 + 8 * 3600000).toISOString(),
    systolic: 122,
    diastolic: 78,
    pulse: 68,
    arm: 'left',
    position: 'sitting',
    medTaken: true,
    medNames: ['Lisinopril 10mg', 'Amlodipine 5mg'],
    notes: 'Morning measurement before breakfast. Felt rested.',
  },
  {
    id: 'rd-02',
    timestamp: new Date(Date.now() - 27 * 86400000 + 20 * 3600000).toISOString(),
    systolic: 128,
    diastolic: 82,
    pulse: 74,
    arm: 'left',
    position: 'sitting',
    medTaken: true,
    medNames: ['Lisinopril 10mg'],
    notes: 'Evening check after work commute.',
  },
  {
    id: 'rd-03',
    timestamp: new Date(Date.now() - 25 * 86400000 + 8 * 3600000).toISOString(),
    systolic: 118,
    diastolic: 76,
    pulse: 66,
    arm: 'right',
    position: 'sitting',
    medTaken: true,
    medNames: ['Lisinopril 10mg', 'Amlodipine 5mg'],
    notes: 'Optimal baseline morning reading.',
  },
  {
    id: 'rd-04',
    timestamp: new Date(Date.now() - 23 * 86400000 + 19 * 3600000).toISOString(),
    systolic: 132,
    diastolic: 84,
    pulse: 78,
    arm: 'left',
    position: 'sitting',
    medTaken: false,
    medNames: [],
    notes: 'Forgot morning dose due to travel.',
  },
  {
    id: 'rd-05',
    timestamp: new Date(Date.now() - 21 * 86400000 + 8 * 3600000).toISOString(),
    systolic: 124,
    diastolic: 80,
    pulse: 70,
    arm: 'left',
    position: 'sitting',
    medTaken: true,
    medNames: ['Lisinopril 10mg', 'Amlodipine 5mg'],
    notes: 'Resumed medication schedule.',
  },
  {
    id: 'rd-06',
    timestamp: new Date(Date.now() - 19 * 86400000 + 21 * 3600000).toISOString(),
    systolic: 119,
    diastolic: 77,
    pulse: 65,
    arm: 'left',
    position: 'sitting',
    medTaken: true,
    medNames: ['Lisinopril 10mg'],
    notes: 'Post-yoga evening check.',
  },
  {
    id: 'rd-07',
    timestamp: new Date(Date.now() - 17 * 86400000 + 8 * 3600000).toISOString(),
    systolic: 126,
    diastolic: 79,
    pulse: 71,
    arm: 'right',
    position: 'sitting',
    medTaken: true,
    medNames: ['Lisinopril 10mg', 'Amlodipine 5mg'],
    notes: 'Steady morning stats.',
  },
  {
    id: 'rd-08',
    timestamp: new Date(Date.now() - 15 * 86400000 + 18 * 3600000).toISOString(),
    systolic: 136,
    diastolic: 88,
    pulse: 82,
    arm: 'left',
    position: 'sitting',
    medTaken: false,
    medNames: [],
    notes: 'High sodium dinner (restaurant takeout).',
  },
  {
    id: 'rd-09',
    timestamp: new Date(Date.now() - 14 * 86400000 + 9 * 3600000).toISOString(),
    systolic: 142,
    diastolic: 91,
    pulse: 84,
    arm: 'left',
    position: 'sitting',
    medTaken: true,
    medNames: ['Lisinopril 10mg', 'Amlodipine 5mg'],
    notes: 'Stage 2 spike. Took medication immediately with full water glass.',
  },
  {
    id: 'rd-10',
    timestamp: new Date(Date.now() - 13 * 86400000 + 8 * 3600000).toISOString(),
    systolic: 125,
    diastolic: 81,
    pulse: 69,
    arm: 'left',
    position: 'sitting',
    medTaken: true,
    medNames: ['Lisinopril 10mg', 'Amlodipine 5mg'],
    notes: 'Recovered closer to target baseline.',
  },
  {
    id: 'rd-11',
    timestamp: new Date(Date.now() - 11 * 86400000 + 20 * 3600000).toISOString(),
    systolic: 121,
    diastolic: 78,
    pulse: 67,
    arm: 'right',
    position: 'sitting',
    medTaken: true,
    medNames: ['Lisinopril 10mg'],
    notes: 'Good evening numbers.',
  },
  {
    id: 'rd-12',
    timestamp: new Date(Date.now() - 9 * 86400000 + 8 * 3600000).toISOString(),
    systolic: 116,
    diastolic: 75,
    pulse: 64,
    arm: 'left',
    position: 'sitting',
    medTaken: true,
    medNames: ['Lisinopril 10mg', 'Amlodipine 5mg'],
    notes: 'Hydrated, full 8 hours sleep.',
  },
  {
    id: 'rd-13',
    timestamp: new Date(Date.now() - 7 * 86400000 + 8 * 3600000).toISOString(),
    systolic: 123,
    diastolic: 79,
    pulse: 70,
    arm: 'left',
    position: 'sitting',
    medTaken: true,
    medNames: ['Lisinopril 10mg', 'Amlodipine 5mg'],
    notes: 'Start of recent 7-day tracking window.',
  },
  {
    id: 'rd-14',
    timestamp: new Date(Date.now() - 5 * 86400000 + 19 * 3600000).toISOString(),
    systolic: 127,
    diastolic: 83,
    pulse: 72,
    arm: 'right',
    position: 'sitting',
    medTaken: true,
    medNames: ['Lisinopril 10mg'],
    notes: 'After brisk 30-min walk and cool-down.',
  },
  {
    id: 'rd-15',
    timestamp: new Date(Date.now() - 3 * 86400000 + 8 * 3600000).toISOString(),
    systolic: 119,
    diastolic: 77,
    pulse: 66,
    arm: 'left',
    position: 'sitting',
    medTaken: true,
    medNames: ['Lisinopril 10mg', 'Amlodipine 5mg'],
    notes: 'Clean morning reading.',
  },
  {
    id: 'rd-16',
    timestamp: new Date(Date.now() - 2 * 86400000 + 20 * 3600000).toISOString(),
    systolic: 122,
    diastolic: 79,
    pulse: 68,
    arm: 'left',
    position: 'sitting',
    medTaken: true,
    medNames: ['Lisinopril 10mg'],
    notes: 'Evening reading.',
  },
  {
    id: 'rd-17',
    timestamp: new Date(Date.now() - 1 * 86400000 + 8 * 3600000).toISOString(),
    systolic: 118,
    diastolic: 76,
    pulse: 65,
    arm: 'left',
    position: 'sitting',
    medTaken: true,
    medNames: ['Lisinopril 10mg', 'Amlodipine 5mg'],
    notes: 'Yesterday morning check. Controlled.',
  },
  {
    id: 'rd-18',
    timestamp: new Date(Date.now() - 6 * 3600000).toISOString(),
    systolic: 120,
    diastolic: 78,
    pulse: 68,
    arm: 'left',
    position: 'sitting',
    medTaken: true,
    medNames: ['Lisinopril 10mg', 'Amlodipine 5mg'],
    notes: 'Today morning log. Ready for the day.',
  },
];

export const DEFAULT_PRESET_MEDICATIONS = [
  'Lisinopril 10mg',
  'Amlodipine 5mg',
  'Metoprolol 25mg',
  'Losartan 50mg',
  'Hydrochlorothiazide 12.5mg',
  'Atorvastatin 20mg',
  'Baby Aspirin 81mg',
];
